apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/nexmotion-lab/comma-authentication/k8s/base?ref=k8s

patches:
  - path: patch-env.yaml
  - path: patch-resource.yaml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: auth-config

images:
  - name: auth-service
    newName: sunwoo3856/authentication
    newTag: latest

replicas:
  - count: 1
    name: auth-service

