apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-service
spec:
  template:
    spec:
      containers:
        - name: diary-service
          resources:
            requests:
              memory: 756Mi
              cpu: "1"
            limits:
              memory: 1G
              cpu: "1"
      